:PROPERTIES:
:ID:       2247a3be-0603-453a-8da6-06d97a2e900e
:END:
#+options: ':nil *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline
#+options: author:t broken-links:nil c:nil creator:nil
#+options: d:(not "LOGBOOK") date:t e:t email:nil f:t inline:t num:t
#+options: p:nil pri:nil prop:nil stat:t tags:t tasks:t tex:t
#+options: timestamp:t title:t toc:t todo:t |:t
#+title: Ley_de_Ohm
#+filetags: :clases:electronica:
#+date: <2026-06-06 Sat>
#+author: Santiago Javier Proaño Yépez
#+email: santiago.proano01@epn.edu.ec
#+language: en
#+select_tags: export
#+exclude_tags: noexport
#+creator: Emacs 29.3 (Org mode 9.6.15)
#+cite_export:
* Ley de Ohm
Nos da la energía que necesitamos para darle a todo el [[id:c164370e-8661-4fe9-9195-776925df8ef4][circuito]]. Aparece en el siglo XIX donde un científico descubrió que la corriente era directamente proporcional al voltaje e inversamente proporcional a la resistencia dando como resultado.
\begin{equation}
I = \frac{V}{R}
\end{equation}

Para usarla de forma mas fácil usar VIR
\begin{equation}
V = I \times R
\end{equation}

Gracias a la ley de ohm podemos calcular la potencia.
* Potencia
La energía $(W)$ es la capacidad de hacer un trabajo, la potencia es la cantidad de tiempo en la que se demora en realizar un trabajo. Por lo tanto:
\begin{equation}
[w] P = \frac{W [J]}{t [s]} 
\end{equation}
Medida en watts. Sin embargo, cuando hablamos de potencia en circuitos, esta se puede expresar con la ley de ohm como:
\begin{equation}
\begin{align}
P = V \times I\\
P = I^{2 }\times R
\end{align}
\end{equation}



