:PROPERTIES:
:ID:       366e289a-215d-4f9b-a575-85ca60f140e5
:END:
#+options: ':nil *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline
#+options: author:t broken-links:nil c:nil creator:nil
#+options: d:(not "LOGBOOK") date:t e:t email:nil f:t inline:t num:t
#+options: p:nil pri:nil prop:nil stat:t tags:t tasks:t tex:t
#+options: timestamp:t title:t toc:t todo:t |:t
#+title: Métodos de integración
#+filetags: :clases:calculo:
#+date: <2026-06-30 Tue>
#+author: Santiago Javier Proaño Yépez
#+email: santiagoproano06@gmail.com
#+language: en
#+select_tags: export
#+exclude_tags: noexport
#+creator: Emacs 29.3 (Org mode 9.6.15)
#+cite_export:
* Métodos de integración
** Tip
*Tip, el prefactor* Cuando vayamos a integrar una función donde
necesitamos un valor para poder integrar ejemplo una integral de una
fracción podemos integrar normalmente y poner el prefactor, que es el
valor de la variable a la menos 1. Ejemplo:
- Ejemplo 1, en este caso pasa lo normal
#+begin_export latex
\[
\int \frac{1}{u - 10} \, du = \ln{u - 10} + C
\]
#+end_export
- Ejemplo 2
  En este caso esto esta mal por que no se esta considerando el numero
  que esta junto con la variable, el $-1$
  
  #+begin_export latex
\[
\int \frac{1}{10 - u} \, du = \ln{u - 10} + C
\]
#+end_export

  Lo correcto, el prefactor seria $-1^{-1} = -1$
  #+begin_export latex
\int \frac{1}{10 - u} \, du = - \ln{u - 10} + C
  #+end_export

- Ejemplo 3
  En este caso también esta mal pues no se considera el prefactor
  #+begin_export latex
\[
\int \frac{1}{2u + 3} \, du = \ln{2u - 3} + C
\]
#+end_export


  Lo correcto seria tomar el prefactor $2^{-1} = \frac}{1}{2}$

  #+begin_export latex
\[
\int \frac{1}{2u + 3} \, du = \frac{1}{2} \cdot \ln{2u - 3} + C
\]
#+end_export
  
** Método de sustitución
:PROPERTIES:
:ID:       a537d4f5-0845-4821-bfb7-98e94da9e6d7
:END:
Básicamente es coger una función de la integral, hacer la [[id:c0e37bde-4ef6-465a-93b5-1596c23fe407][Derivación]] y
reemplazar, el objetivo es hacer una integral más fácil. Sea la integral:
#+begin_export latex
\[
\int (3x - 5)^{4} \, dx
\]
#+end_export

podemos tomar la variable $u = 3x - 5$ entonces derivamos a ambos
lados:
#+begin_export latex
\[
\begin{align}
u = 3x -5 \\
du = 3 dx
\end{align}
\]
#+end_export

Luego despejamos $dx$ o buscamos que quede lo mismo que tiene $dx$
según nos convenga:
#+begin_export latex
\[
dx = \frac{du}{3}
\]
#+end_export
 Ahora remplazamos en la integral original, la cosa es que nos quede
 todo en función de $u$

 #+begin_export latex
\[
\int (u)^{4} \frac{1}{3} \, du
\]
#+end_export

 teniendo esto sacamos la constante e integramos normalmente:
#+begin_export latex
\[
\begin{align}
\frac{1}{3} \int (u)^{4} \, du\\
\frac{1}{3} \frac{u^{5}}{5} + C
\end{align}
\]
#+end_export

Al final solo remplazamos la u original y ya esta.
#+begin_export latex
\[
\begin{align}
\frac{1}{3} \frac{(3x - 5)^{5}}{5} + C\\
\frac{(3x - 5)^{5}}{15} + C
\end{align}
\]
#+end_export


** Fracciones parciales
Básicamente se separa una fracción con variables de un grado menor se
las suma, se iguala, se resuelve el sistema de ecuaciones, se remplaza
y por ultimo se resuelve. Sea una función $f(x)$ tal que:
#+begin_export latex
\[
\frac{1}{(u+1)(u+2)}
\]
#+end_export
lo que hacemos para integrarle es
1. Separar la función en dos fracciones donde arriba este una
   variable o una función con un grado menor al que esta abajo

   #+begin_export latex
\[
\frac{A}{(u+1)} + \frac{B}{u+2}
\]
#+end_export

2. Volvemos a sumar las fracciones para que lo de abajo este junto de
   nuevo

   #+begin_export latex
\[
\frac{A(u+2) + B(u+1)}{(u+1)(u+2)}
\]
#+end_export

#+begin_export latex
\[
\frac{uA + 2A + uB + B}{(u+1)(u+2)}
\]
#+end_export
3. Como todo estaba igualado a su forma original podemos simplificar
   lo de abajo

   #+begin_export latex
\[
1 = uA + 2A + uB + B
\]
#+end_export 
4. Juntamos todo lo que tiene u's y todo lo que no

   #+begin_export latex
\[
1 = u(A + B) + (2A + B)
\]
#+end_export
5. Igualar para tener dos ecuaciones

   #+begin_export latex
\[
0U + 1 = u(A + B) + (2A + B)
\]
#+end_export
   Si te das cuenta lo que tiene u a la izquierda debe ser lo mismo
   que tiene u a la derecha y asi

   #+begin_export latex
\[
\begin{cases}
A + B = 0\\
2A + B =1
\end{cases}
\]
#+end_export

   Resolvemos el sistema de ecuaciones y obtenemos los valores, mismos
   que remplazamos en las fracciones y volvemos a integrar

   #+begin_export latex
\[
\begin{align}
   A = 1\\
   B = -1
 \end{align}
\]
#+end_export


#+begin_export latex
\[
\int \frac{1}{(u + 1)} \, du + \int \frac{-1}{(u + 2)} \, du
\]
#+end_export
y eso ya es una [[id:b29281cc-0a38-4348-9afc-e9c10affcc07][I. de una fracción]]


** Integración por partes
Básicamente, y parecido al [[id:a537d4f5-0845-4821-bfb7-98e94da9e6d7][Método de sustitución]], se toman en este
caso dos variables $u$ y $dv$ se integra y deriva respecivamente y se
aplica la formula:
*Un día Vi = Una Vaca - Vestida De Uniforme*
Es decir:
#+begin_export latex
\[
\int u \, dv = u \cdot v - \int v \, du
\]
#+end_export
Sea la integral:

#+begin_export latex
\[
\int x \cdot e^{x} \, dx
\]
#+end_export

Se toma en este caso a $u$ como una fácil de derivar y a $dv$ como una
fácil de integrar, también se toma a $dx$. Normalmente se escoge a $v$ siguiendo el acrónimo
ILATE (aunque a estebitan no le gustaba dicho acrónimo jaja):

I: inversas $f(x)^{-1}$
L: Logarítmicas
A: Algebraicas
T: Trigonométricas
E: Exponenciales $e^{x}$

#+begin_export latex
\[
\begin{align}
u = x\\
dv = e^{x} dx
\end{align}
\]
#+end_export

Seleccionadas, se deriva a $u$ para obtener $du$
#+begin_export latex
\[
du = 1 dx = dx 
\]
#+end_export

Luego se integra $dv$ para obtener $v$ (las constantes se fueron se
sabático xdxd)
#+begin_export latex
\[
\begin{align}
\int \, dv = \int e^{x} \, dx\\
v = e^{x} 
\end{align}
\]
#+end_export

Luego remplazamos en la vaca vestida de uniforme
#+begin_export latex
\[
\int x e^{x} dx = x \cdot e^{x} - \int e^{x} dx
\]
#+end_export

Y resolvemos, y ya.
#+begin_export latex
\[
= xe^{x} - e^{x} + C
\]
#+end_export
